// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/inference/inference.proto

package inference

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PredictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelName     string                 `protobuf:"bytes,1,opt,name=ModelName,proto3" json:"ModelName,omitempty"`
	InputData     []byte                 `protobuf:"bytes,2,opt,name=InputData,proto3" json:"InputData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictRequest) Reset() {
	*x = PredictRequest{}
	mi := &file_proto_inference_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRequest) ProtoMessage() {}

func (x *PredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRequest.ProtoReflect.Descriptor instead.
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return file_proto_inference_inference_proto_rawDescGZIP(), []int{0}
}

func (x *PredictRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *PredictRequest) GetInputData() []byte {
	if x != nil {
		return x.InputData
	}
	return nil
}

type PredictResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutputData    []byte                 `protobuf:"bytes,1,opt,name=OutputData,proto3" json:"OutputData,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictResponse) Reset() {
	*x = PredictResponse{}
	mi := &file_proto_inference_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictResponse) ProtoMessage() {}

func (x *PredictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictResponse.ProtoReflect.Descriptor instead.
func (*PredictResponse) Descriptor() ([]byte, []int) {
	return file_proto_inference_inference_proto_rawDescGZIP(), []int{1}
}

func (x *PredictResponse) GetOutputData() []byte {
	if x != nil {
		return x.OutputData
	}
	return nil
}

func (x *PredictResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_inference_inference_proto protoreflect.FileDescriptor

const file_proto_inference_inference_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/inference/inference.proto\x12\tinference\"L\n" +
	"\x0ePredictRequest\x12\x1c\n" +
	"\tModelName\x18\x01 \x01(\tR\tModelName\x12\x1c\n" +
	"\tInputData\x18\x02 \x01(\fR\tInputData\"I\n" +
	"\x0fPredictResponse\x12\x1e\n" +
	"\n" +
	"OutputData\x18\x01 \x01(\fR\n" +
	"OutputData\x12\x16\n" +
	"\x06Status\x18\x02 \x01(\tR\x06Status2O\n" +
	"\tInference\x12B\n" +
	"\aPredict\x12\x19.inference.PredictRequest\x1a\x1a.inference.PredictResponse\"\x00BEZCgithub.com/arhantsg07/ml-inference-system/proto/inference;inferenceb\x06proto3"

var (
	file_proto_inference_inference_proto_rawDescOnce sync.Once
	file_proto_inference_inference_proto_rawDescData []byte
)

func file_proto_inference_inference_proto_rawDescGZIP() []byte {
	file_proto_inference_inference_proto_rawDescOnce.Do(func() {
		file_proto_inference_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inference_inference_proto_rawDesc), len(file_proto_inference_inference_proto_rawDesc)))
	})
	return file_proto_inference_inference_proto_rawDescData
}

var file_proto_inference_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_inference_inference_proto_goTypes = []any{
	(*PredictRequest)(nil),  // 0: inference.PredictRequest
	(*PredictResponse)(nil), // 1: inference.PredictResponse
}
var file_proto_inference_inference_proto_depIdxs = []int32{
	0, // 0: inference.Inference.Predict:input_type -> inference.PredictRequest
	1, // 1: inference.Inference.Predict:output_type -> inference.PredictResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_inference_inference_proto_init() }
func file_proto_inference_inference_proto_init() {
	if File_proto_inference_inference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inference_inference_proto_rawDesc), len(file_proto_inference_inference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inference_inference_proto_goTypes,
		DependencyIndexes: file_proto_inference_inference_proto_depIdxs,
		MessageInfos:      file_proto_inference_inference_proto_msgTypes,
	}.Build()
	File_proto_inference_inference_proto = out.File
	file_proto_inference_inference_proto_goTypes = nil
	file_proto_inference_inference_proto_depIdxs = nil
}
