package main

import (
	"context"
	"flag"
	"log"
	"time"

	pb "github.com/arhantsg07/ml-inference-system/proto/inference"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
)

var (
	serverAddr = flag.String("addr", "localhost:50051", "The server address in the format of host:port")
)

/*
* Make prediction function takes the client interface generated by proto code
* which is accessed by the client API that the generated code files expose
* Takes the predict request defined in the proto file, logs the err if failed
* else prints the prediction (the prediction is harcoded for now)
*/

func MakePrediction(client pb.InferenceClient, req *pb.PredictRequest) {
	log.Printf("Getting the prediction from the model %s for the input %x", req.ModelName, req.InputData)
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	prediction, err := client.Predict(ctx, req)
	if err != nil {
		log.Printf("client.Predict failed: %v", err)
	}
	log.Println(prediction)
}

/*
* The main declares the opts array that is used to set credentials (auth, TLS, JWT, etc)
* as mentioned in the official docs : https://grpc.io/docs/languages/go/basics/
* a client is created and established using the API exposed by the proto code files
* (pb.NewInferenceClient)
*/

func main() {
	var opts []grpc.DialOption
	opts = append(opts, grpc.WithTransportCredentials(insecure.NewCredentials()))
	conn, err := grpc.NewClient(*serverAddr, opts...)
	if err != nil {
		log.Fatalf("fail to dial: %v", err)
	}
	defer conn.Close()
	client := pb.NewInferenceClient(conn)
	MakePrediction(client, &pb.PredictRequest{})
}
